sudo: required
language: ruby
services:
- docker
script:
- docker build --tag strothj/ansible .
deploy:
  provider: script
  script: chmod +x ./deploy.sh && ./deploy.sh
  on:
    branch: master
env:
  global:
  - secure: cTthKYLMYewLLn1sJKvv6uuEGvfLHnuY2sTMJ99GhZxX622E580oHrsVT3KJO+X0JmQKZ2ezCvhq1TdbJoUGWPioscn+tfWx/nosZZFIYnMc8uE+xx1h1RoLEhJ8XUqSOEjM0IfByyGc4IZb705mot2oF4MOpLuWcx9XK0fr0q8VTsJ/0OaiuFdfALMJonmhnRmPl51WmUOqLiIW/YasxCV8EeyBwN3NGkfYtMzyDqvtt18t5K5lOo+W5u0Fqx/0DqWwFpAqjORY0Ox+Fdtcg6zmKRAdYsXMsPzmCXA7Hdc2XQm+rH3sQS1zejVWqtemBbmCjEzg6L4tjziRQ43UNd9OwB602MLCrmVanKz1BnGvWHfCpcSpCqplIyIvB+QMsfrathinP0YGouTC+PIm7SvM/g3VZHV9c5FF+Iw2mfgHvPgOpOKrANx7XEf+6BaX8B5zVodZPx6eSdMbNVRjkn9Fyja/C0EiVmiDiTwRt99F07yj99u1j/m7BHtS1AhNDkod2XAtzlZFUraUn9usJgji9dS1PA1WCYoy39ui8GZfOFOTU4rvz/vezM1UF5PtCFc7YkIXv7jzTbIORP/bbafvxV3EHJLnIISJVl/RDSIbvcP/1T7K0uDM41r8Rng5Ln6/OFQbbvywAyfe+llygdxsRXmv+YajroM2yrEdhzg=
  - secure: ZSl4IwAELcQobjCflv+QpCG1E8n6lLFfP1fFznLjP2mBr8t6PsqcX3tSMatZusZsPMr7J+oZSKOW8YafWWa0X6EJcZlXH+NX3qNunV9AD3cCj4OGK1bfW8mZag7psqMUsa3BrscaAwhoqrtZGjvgm5SKIVoWzHPivAS1oNTlee7UjLXUDb2R+R+6EUIYt4rakXcSI4FaiEDYJyXNrrFzMMktiuKdmc/q5vZN2safBJz2TSMDVSCsQhukjdV2kccCl6YmL4I9uR4O0sIB+HdvLQE4w9egXWfnZh17Q5/Hyk+Dv4PxCcrjdtjN+n1FI4fb6qk8d1G1xZThgo5f/py4wtEBcNw3KJCP0vrqQS/66eMTW6VlUkJ/KLUUMORZrJPHj3T07ZoMTun9DmPgMy5wNUULyKEwxRAFujhP50G6KzA7krmcXUVLeZSlAUnYH43tdaLeD01zJn1vw2H9hlu2sCNy7N6jvRbeIyhnsBLxcHBYlq+fDbN4N3EKU51KGkxmS8G8GL9Tx2xeSWdhU5PLa+8Xj/EI1qXf0+wZ6cMPg94dyTX7djZOeF8InQfMLqHXfUSfcp5CNk6VyNu6R9EQX3g6gvqjvwtMeOSHUAR7FzCS8m+YEt22+sGLjcagrkGinl3pOg/iUzlv2OEMSZu9OD/pIKo0Re/N5rJmHsfPHQQ=
